### ISSUE TITLE
Why don't use the official plugin here: https://github.com/labstack/echo-contrib/tree/master/casbin

### ISSUE THREAD

**Issue by hsluoyz** [paysuper/echo-casbin-middleware#2]
Why don't use the official plugin here: https://github.com/labstack/echo-contrib/tree/master/casbin

**Comment by vtolstov** [comment]
This middleware works with remote casbin, official works with only local.

**Comment by hsluoyz** [comment]
Thanks for the explanation. I have added it to the client list: https://github.com/casbin/casbin-server#architecture :)

**Comment by vtolstov** [comment]
I'm also create alternative casbin server that uses go-micro. Later i can
share it.

сб, 27 июл. 2019 г., 17:22 Yang Luo <notifications@github.com>:

**Comment by hsluoyz** [comment]
Good to hear this news !
